### PR TITLE
Use cosmiconfig for config variety

### LINKED ISSUE #330: Support an external config file instead of just package.json config
[Issuehunt badges](https://issuehunt.io/r/xojs/xo/issues/330)

This is somewhat of a similar ask to #250, but with a little different use context: 

I'd like to put my XO configuration in a separate file (`.xorc.*`), just like how [ESLint](https://eslint.org/docs/user-guide/configuring#using-configuration-files) and [Prettier](https://prettier.io/docs/en/configuration.html) do it.

Having all of those config options in a single file really clutters up my `package.json`, and I'd like to be able to more easily copy/symlink files from a central location, instead of having to copy/paste configurations into my `package.json` every time.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)

### Submitted pull Requests
- [#425 Find XO config based on linted file path](https://issuehunt.io/r/xojs/xo/pull/425)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/xojs/xo/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by j0hnm4r5**
Fixes #330

### CODE REVIEW

**Comment by j0hnm4r5** [comment]
This seems to be working so far on my machine, using the forked repo, but I'm not nesting any `package.json`s or `.xorc`s. There's a few tests failing, but I think it's because they were written _specifically_ to check for `pkg-conf`'s handling of the config.

Annoyingly, while using a `.xorc`, you have to reload VSCode if you make any changes to the config; it [seems like](https://github.com/Microsoft/vscode-eslint/commit/754f8bcdc0a6436dd79c98c013ee87117c0e702c) VSCode watches `.eslintrc` and `package.json` for changes, which is why a reload isn't necessary when using those. But that's not a big deal in the grand scheme of things (and those tat want to continue doing config in `package.json` won't be affected at all).

**Comment by aslafy-z** [comment]
Any chance you rebase your work?

**Comment by sindresorhus** [comment]
See: https://github.com/xojs/xo/pull/279#issuecomment-407250935

Can you also fix the merge conflict?

This will need some docs and test additions too.

**Comment by bunysae** [comment]
@j0hnm4r5 
Do you want to do any on further work on this pull-request?

**Pull request closed without merging**
