### PR TITLE
 Turn all paths `cwd`-relative before linting

### LINKED ISSUE #223: Overrides not working when calling xo with absolute paths
I have this in my package.json:

```json
"xo": {
  "extends": "xo-react",
  "parser": "babel-eslint",
  "plugins": ["react"],
  "envs": ["node", "browser"],
  "rules": {
    "react/forbid-component-props": 0,
    "react/jsx-closing-bracket-location": ["error", "tag-aligned"]
  },
  "overrides": [{
    "files": "src/client/components/*.js",
    "rules": {
      "unicorn/filename-case": [
        "error", {"case": "pascalCase"}
      ]
    }
  }, {
    "files": "src/client/containers/*.js",
    "rules": {
      "unicorn/filename-case": [
        "error",
        {"case": "pascalCase"}
      ]
    }
  }]
}
```

And I have the file `src/client/components/ExtendedReferenceManyField.js`

Now, if I call

```
$ xo src/client/components/ExtendedReferenceManyField.js
```

it finishes without errors. However, calling:

```
$ xo /home/user/dev/project/src/client/components/ExtendedReferenceManyField.js
```

will output:

```
  src/client/components/ExtendedReferenceManyField.js:1:1
  ✖  1:1  Filename is not in kebab case. Rename it to extended-reference-many-field.js.  unicorn/filename-case

  1 error
```

I stumbled on this while using [lint-staged](https://github.com/okonet/lint-staged) in my project.

---

**xo version**: 0.18.2
**Node version**: 6.10.1
**OS**: Linux Mint 18 Cinnamon 64-bit

### PR DESCRIPTION
**Pull request by futpib**
fix #223

### CODE REVIEW

**Comment by sindresorhus** [comment]
It feels weird to turn paths relative. What if the overrides specify absolute paths? Wouldn't it make more sense to make the overrides paths absolute instead?

**Comment by futpib** [comment]
> What if the overrides specify absolute paths?

Should overrides even support absolute paths? If you put an absolute path override in you `package.json` it probably won't work on anyone else's setup or in CI. For instance `/Users/zanona/Developer/my-app/packages/shop-app/**` (from https://github.com/xojs/xo/issues/223#issuecomment-354548646) clearly won't work for anyone else (username is in the path, the path is Mac-specific, etc.)

> Wouldn't it make more sense to make the overrides paths absolute instead?

Would be hard to do this correctly since override paths are `minimatch` globs.

**Comment by sindresorhus** [comment]
That's a good point.

**Comment by sindresorhus** [comment]
You need to add this PR to https://issuehunt.io/r/xojs/xo/issues/223 to get the bounty.

**Comment by niftylettuce** [comment]
@sindresorhus 	Can you please release a new version to NPM?  The last release was January and this fix resolves issues with people using `lint-staged`.

**Comment by okanthony** [comment]
@sindresorhus ditto ^^ 🙏 

@niftylettuce in the meantime you could always use a git URL to point to `master` in your `package.json`

**Pull request merged**
