### PR TITLE
Add `print-config` option

### PR DESCRIPTION
**Pull request by teehemkay**
Essentially mimics `eslint` [`--print-config`](https://eslint.org/docs/user-guide/command-line-interface#--print-config) option.

Related to #272 and #309.

As an added bonus, this feature enables the use of `xo` as a drop-in replacement for the global `eslint` executable when using the [`eslint-javascript`](http://www.flycheck.org/en/latest/languages.html#javascript) linter of FlyCheck, the popular GNU Emacs syntax checking tool.

### CODE REVIEW

**Comment by pvdlg** [comment]
Thanks for the PR!

XO as as ESLint allows to create specific config for a subset of files with `overrides`. However they work quite differently:
- Eslint `overrides` cannot contains `extends` XO's can
- XO `overrides` can contain XO options (`space`, `semicolon`, etc...) but ESLint can't

How do you handle those cases? Is your PR produces a valid ESLint config for the following XO config?
```json
{
  "overrides": [
    {
      "files": "test/*.js",
      "extends": "some-custom-config",
      "esnext": false,
      "space": 3
    },
    {
      "files": "test/foo.js",
      "esnext": true
    }
  ]
}
```

**Comment by teehemkay** [comment]
I was also thinking about actually having two options: 
The first one would return the config as pre-processed by XO (_ie_, before sending it to Eslint). This would enable debugging the XO pre-processing. Suggested name would be something like `--print-xo-config` 
The second one would be the current PR.
Any thoughts about this suggestion?

**Comment by pvdlg** [comment]
In order to debug the XO pre-processing we can use [debug](https://github.com/visionmedia/debug) with possible a `--debug` CLI argument. But that would be another PR.

So I don't think there is really a need for 2 options. The objective is to generate a single config file that can be used directly with `ESLint`.

I try to look at this functionality a while ago and I couldn't figure out a way to "translate" XO certain `overrides` use case into ESLint `overrides` as they have some differences.

**Comment by teehemkay** [comment]
Sorry for the confusion.

As I wrote in my initial comment, this PR

> Essentially mimics `eslint` [`--print-config`](https://eslint.org/docs/user-guide/command-line-interface#--print-config) option.

It's only _related_ to #272 and #309 

The PR pre-processes `xo` options and then pass them to the `eslint` function that implements the `print-config` option. It's the later that does the heavy lifting of generating the config.

Since `print-config` is only concerned with a single file, we only need to make sure to pull in any _overriding_ option _that needs to be applied_ to the file. 

So, unless I'm mistaken, the `eslint` override feature does not seem to be relevant here.

My motivation in implementing this PR, is to enable `xo` to act as as a drop-in replacement (sill some work to do) for `eslint` when using ['FlyCheck`](http://www.flycheck.org/en/latest/languages.html#javascript) which seems to be the most popular  `Emacs` linter.

**Comment by teehemkay** [comment]
Closed the PR since it doesn't seem to be going anywhere.

**Pull request closed without merging**
