### PR TITLE
Find XO config based on linted file path

### LINKED ISSUE #65: A way to override the default ignores
[Issuehunt badges](https://issuehunt.io/r/xojs/xo/issues/65)

Right now it's not possible to lint anything in a `fixtures` directory, even if you want to. There should be a way to enable that. 

I tried this: 

``` js
{
  "xo": {
    "ignore": [
      "!{test/,}fixture{s,}/**"
    ]
  }
}
```

But no luck

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)

### Submitted pull Requests
- [#425 Find XO config based on linted file path](https://issuehunt.io/r/xojs/xo/pull/425)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/xojs/xo/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### LINKED ISSUE #330: Support an external config file instead of just package.json config
[Issuehunt badges](https://issuehunt.io/r/xojs/xo/issues/330)

This is somewhat of a similar ask to #250, but with a little different use context: 

I'd like to put my XO configuration in a separate file (`.xorc.*`), just like how [ESLint](https://eslint.org/docs/user-guide/configuring#using-configuration-files) and [Prettier](https://prettier.io/docs/en/configuration.html) do it.

Having all of those config options in a single file really clutters up my `package.json`, and I'd like to be able to more easily copy/symlink files from a central location, instead of having to copy/paste configurations into my `package.json` every time.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)

### Submitted pull Requests
- [#425 Find XO config based on linted file path](https://issuehunt.io/r/xojs/xo/pull/425)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/xojs/xo/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### PR DESCRIPTION
**Pull request by pvdlg**
fix #331, fix #279, fix #330, fix #420, fix #65

This change the way to load the XO config files. Instead of looking for the config in directly `cwd` we now search for a config file starting from the directory of each linted and by walking up parent directories.

The config files supported are now: `pacakge.json`, `.xorc` (JSON only), `.xorc.json`, `.xorc.js`, `xo.config.js`

This PR will help to implement #373 as we can now build a different config per file mode easily. That will allow us to apply the Typescript rules only to the `.ts`/`.tsx` files.

A few other things incidentally added by the PR:
- #65 is now fixed
- SamVerschueren/vscode-linter-xo#58 should be fixed without any changes in `vscode-linter-xo`
- `lintFiles` is now completely async allowing to parallelise looking for config files (async) with building/merginf config (sync)
- Reorganized the code a little bit for clarity as the files and function started to be quite large
- Replace `multimatch` with `micromatch` as it's the library used by `globby` which is already in the dependency tree

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Referenced issues

This pull request has been submitted to:
- [#65: A way to override the default ignores](https://issuehunt.io/repos/40053602/issues/65)
- [#330: Support an external config file instead of just package.json config](https://issuehunt.io/repos/40053602/issues/330)
---

IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

### CODE REVIEW

**Comment by sindresorhus** [comment]
Yay! This is really awesome 🙌

---

> The config files supported are now: pacakge.json, .xorc (JSON only), .xorc.json, .xorc.js, xo.config.js

Can we make it:

- `.xorc` => `.xo-config`
- `.xorc.json` => `.xo-config.json`

And maybe drop `.xorc.js` since there's already `xo.config.js`?

**Comment by sindresorhus** [comment]
> And maybe drop .xorc.js since there's already xo.config.js?

Hmm, I guess it can be useful if you want to hide it. But should be `.xorc.js` => `.xo-config.js`

**Comment by sindresorhus** [comment]
> #65 is now fixed

🎉 Could you add a short readme example to show the user that this is possible?

**Comment by pvdlg** [comment]
> Can we make it:
> - .xorc => .xo-config
> - .xorc.json => .xo-config.json

That's really common among JS project to have  the config files being based on the package name (without a `-config`) for example `.prettierrc` or `.eslintrc` and not `.prettier-config` or `.eslint-config`. I think that breaking from this convention would be confusing and error prone for users.

It would also create a discrepancy between the `package.json` property, the json files and the JS files.

**Comment by pvdlg** [comment]
> 🎉 Could you add a short readme example to show the user that this is possible?

Added a Tips

**Comment by sindresorhus** [comment]
> That's really common among JS project to have the config files being based on the package name (without a -config)

And it's still based on the package name. We're just replacing `rc` with `-config` for clarity.

I just don't like the `rc` suffix. It only makes sense if you know what https://github.com/dominictarr/rc is, and I've been in Node.js for years and I don't really know what `rc` stands for. "resource configs"?. And by not having a separator, it's not always clear what it is. `.xorc`, reads to me as `xorc`, not `xo rc`. What if the package name was `co`. Then the file would be `.corc`.

> I think that breaking from this convention would be confusing and error prone for users.

I honestly think the convention with `rc` is more confusing than not following the convention. `xo-config` makes it totally clear what it is. No questions asked. Imagine a newbie getting into JS, cloning a random project, and seeing a `.xorc` file without knowing what XO or `rc` is. Do you think they immediately realize it's config file?

> It would also create a discrepancy between the package.json property, the json files and the JS files.

The package.json property is `xo`, the current filename is `xorc`. There's already a discrepancy. `-config` is not any more of a discrepancy than `rc`.

**Comment by pvdlg** [comment]
Made the change for config file name

**Comment by sindresorhus** [comment]
There's a slight regression in the code coverage: https://coveralls.io/builds/28770195/source?filename=lib/options-manager.js#L261

Otherwise, this looks good to me. When merged, should I do a new release or do you plan other changes soon?

**Comment by pvdlg** [comment]
> There's a slight regression in the code coverage: https://coveralls.io/builds/28770195/source?filename=lib/options-manager.js#L261

That was on line 303 before and wasn't tested either.
I improve the test coverage for the part I changes that changed

**Comment by pvdlg** [comment]
> Otherwise, this looks good to me. When merged, should I do a new release or do you plan other changes soon?

I'm working on the Typescript support today. Not sure if I'll finish by the end of day. If I don't open the PR today, it will probably take a few days.

**Comment by sindresorhus** [comment]
Weird, not sure why Coveralls said the coverage fell then 🤷‍♂️

**Comment by sindresorhus** [comment]
> I'm working on the Typescript support today. Not sure if I'll finish by the end of day. If I don't open the PR today, it will probably take a few days.

Sounds good. Then I'll wait. Take your time. I was really just wondering whether anything would happen in the next few weeks for it to be worth waiting for.

**Comment by sindresorhus** [comment]
Thank you so much for working on this. This is such a great improvement 🙌

**Pull request merged**
