### PR TITLE
Respect `.eslintignore`

### PR DESCRIPTION
**Pull request by kevinastone**
Filteres out paths that eslint recognizes as ignored (using the various
`eslintignore` configurations)

This cuts down on noise when the given file is already ignored via
eslint configuration.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Code looks good. Can you document this behavior in the readme?

**Comment by sindresorhus** [comment]
There's already a way to ignore files in XO. This should be documented there.

And you need to fix the merge conflict ;)

**Comment by kevinastone** [comment]
There ya go....

**Comment by sindresorhus** [comment]
Thanks :)

**Comment by sindresorhus** [comment]
@kevinastone Hmm, this break Travis on Windows: https://travis-ci.org/xojs/xo/jobs/589497747

**Comment by kevinastone** [comment]
I'll take a look.

**Comment by kevinastone** [comment]
This doesn't look very cross-platform:
https://github.com/xojs/xo/blob/eae34dbad5d35d1e16329cb0d5948125a038e5ab/test/lint-files.js#L126

**Comment by kevinastone** [comment]
@sindresorhus #401 has the fix (errant trailing slash tripped up paths on windows).

**Pull request merged**
