### PR TITLE
Re-enable `eslint-plugin-promise`

### PR DESCRIPTION
**Pull request by fisker**
Disabled in https://github.com/xojs/xo/commit/dddc991a9e1a96993f6455bfe166dc15c2b80d7e

### CODE REVIEW

**Comment by fisker** [comment]
Didn't see https://github.com/xojs/xo/commit/dddc991a9e1a96993f6455bfe166dc15c2b80d7e#r67879026, feel free to close if you don't want to enable it.

**Comment by sindresorhus** [comment]
I'll think about it. We can keep this open for now.

**Comment by fregante** [comment]
v6 supports it:

- https://github.com/eslint-community/eslint-plugin-promise/pull/219

**Comment by fregante** [comment]
Might be a good time to close it or merge it 🙏

**Pull request merged**
