### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by fregante**
Globby is 2 versions behind, I'm gonna try to update it.

For now, here's every other dependency updated

### CODE REVIEW

**Comment by sindresorhus** [comment]
> Globby is 2

Intentionally. I was waiting for fast-glob. https://github.com/mrmlnc/fast-glob/issues/240

**Comment by fregante** [comment]
I was wondering why it wasn’t updated, I assumed it just needed some work due to breaking changes. 

What do you want to do with this PR then? Merge as is?

**Comment by sindresorhus** [comment]
Is there something you need in these dependencies? Because I already did a "major" release 20 days ago, so not sure we should do it so soon again. I'm trying to not release too often.

**Comment by fregante** [comment]
> Is there something you need in these dependencies?

Not really, it was supposed to be a "let's update everything and see what breaks" PR

**Pull request closed without merging**
